"""
bime/curate_data.py

Reads Synthea CSV output and produces the three app-ready CSV files for the
BIME digital-twins demo of the IDA Underdiagnosis Streamlit app:

  bime/data/patients.csv
  bime/data/hb_trajectories.csv
  bime/data/diagnoses.csv

Synthea must be run first — see bime/README_synthea.md.

Usage:
  python bime/curate_data.py
  python bime/curate_data.py --synthea-dir /path/to/synthea/output/csv
  python bime/curate_data.py --seed 123

What this script does:
  1. Filters Synthea patients: female, age 18–65, alive
  2. Extracts longitudinal HB measurements (LOINC 718-7) — ≥3 per patient
  3. Computes personalized reference interval (perRI) per patient:
       setpoint = mean of up to 5 historical HB values
       sigma    = std of those values
       ci       = setpoint ± 1.96 * sigma
       drop     = setpoint − most_recent_hb
  4. Assigns hb_bin, delta_bin, bucket, Priority (mirrors src/helper.py)
  5. Simulates ferritin via log-normal model (Synthea does not generate it)
  6. Maps SNOMED-CT conditions → ICD-10 via embedded crosswalk
  7. Anonymizes patient UUIDs via SHA-256 → 12-char hex
  8. Writes output CSVs with no PII
"""

import argparse
import hashlib
from pathlib import Path

import numpy as np
import pandas as pd

# ── Paths ──────────────────────────────────────────────────────────────────
BIME_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BIME_DIR / "data"
DEFAULT_SYNTHEA_DIR = BIME_DIR / "synthea_output" / "csv"

# ── LOINC codes ─────────────────────────────────────────────────────────────
HB_LOINC = "718-7"        # Hemoglobin [Mass/volume] in Blood
FERRITIN_LOINC = "2276-4" # Ferritin — NOT generated by Synthea's anemia module

# ── perRI parameters ────────────────────────────────────────────────────────
MIN_HB_MEASUREMENTS = 3   # Minimum total readings required (history + current)
MAX_SETPOINT_TESTS = 5    # Cap on historical readings used to compute setpoint

# ── Binning — mirrors src/helper.py exactly ─────────────────────────────────
DELTA_BINS = [-0.5, 0.5, 1.0, np.inf]
DELTA_LABELS = ["[-0.5, 0.5)", "[0.5, 1)", "[1, inf)"]
DELTA_TIER = {"[-0.5, 0.5)": 1, "[0.5, 1)": 2, "[1, inf)": 3}

HB_LABELS = ["HB < 12.5", "HB ≤ 14.5"]  # Patients above 14.5 are excluded

DELTA_TIER_WEIGHT = 10
HB_LOW_WEIGHT, HB_NORM_WEIGHT = 10, 5
HEALTHY_BONUS = 1

NORMAL_ENCOUNTER_KEYWORDS = [
    "encounter for general adult medical examination",
    "routine",
    "screening",
    "without abnormal findings",
    "wellness",
    "general examination",
]

# ── SNOMED-CT → ICD-10 crosswalk ────────────────────────────────────────────
# Synthea conditions.csv uses SNOMED-CT codes. This crosswalk covers the most
# common codes generated by the anemia module and general Synthea modules.
# Conditions without a mapping are retained with an empty icd10_code.
SNOMED_TO_ICD10 = {
    # Anemia / Iron
    "271737000": "D64.9",   # Anemia (disorder)
    "87522002":  "D50.9",   # Iron deficiency anemia
    "234347009": "D50.9",   # Anemia due to iron deficiency
    "713048008": "D64.9",   # Normocytic anemia
    "448235001": "D53.9",   # Macrocytic anemia
    "14759004":  "D53.1",   # Megaloblastic anemia
    "35240004":  "E61.1",   # Iron deficiency without anemia
    # Metabolic
    "44054006":  "E11.9",   # Type 2 diabetes mellitus
    "15777000":  "E11.65",  # Prediabetes
    "55822004":  "E78.5",   # Hyperlipidemia
    "162864005": "E66.9",   # Obesity
    # Cardiovascular
    "38341003":  "I10",     # Essential hypertension
    "84114007":  "I50.9",   # Heart failure
    "22298006":  "I21.9",   # Myocardial infarction
    "230690007": "I63.9",   # Cerebrovascular accident (stroke)
    # Respiratory
    "195967001": "J45.909", # Asthma
    "13645005":  "J44.1",   # COPD with exacerbation
    "10509002":  "J06.9",   # Acute upper respiratory infection
    "444814009": "J06.9",   # Viral upper respiratory infection
    "36971009":  "J01.90",  # Acute sinusitis
    "40055000":  "J32.9",   # Chronic sinusitis
    # Musculoskeletal
    "82423001":  "M54.5",   # Chronic low back pain
    "57676002":  "M79.3",   # Joint pain
    "67782005":  "M06.9",   # Rheumatoid arthritis
    "203082005": "M81.0",   # Age-related osteoporosis
    "90560007":  "M10.9",   # Gout
    # Mental health
    "386806002": "F32.9",   # Cognitive impairment
    "35489007":  "F32.9",   # Depressive disorder
    "23685000":  "F41.1",   # Anxiety disorder
    # Other common
    "73430006":  "G47.00",  # Sleep disorder
    "40930008":  "E03.9",   # Hypothyroidism
    "59621000":  "I10",     # Essential hypertension (alt code)
    "59820001":  "E78.00",  # Hypercholesterolemia
    "230690007": "I63.9",   # Stroke
    "267036007": "R06.00",  # Dyspnea
    "57054005":  "R55",     # Syncope
    "161891005": "M54.5",   # Low back pain
    "5602001":   "K57.30",  # Diverticulosis
    "68505006":  "N84.0",   # Uterine polyp
    "266599000": "N92.1",   # Menorrhagia
    "276508000": "O26.3",   # Retained intrauterine contraceptive device
    "36992009":  "N39.0",   # Urinary tract infection
    "399211009": "Z87.39",  # History of stroke
    "284551006": "S52.509A",# Fracture of forearm
}

# ── Encounter class → department name + specialty ───────────────────────────
ENCOUNTER_CLASS_MAP = {
    "ambulatory":  ("Primary Care Clinic", "Family Medicine"),
    "wellness":    ("Preventive Health Clinic", "Family Medicine"),
    "outpatient":  ("Outpatient Clinic", "Internal Medicine"),
    "urgentcare":  ("Urgent Care", "Emergency Medicine"),
    "emergency":   ("Emergency Department", "Emergency Medicine"),
    "inpatient":   ("Hospital Inpatient", "Hospital Medicine"),
    "virtual":     ("Telehealth", "Family Medicine"),
}


# ── Utility ──────────────────────────────────────────────────────────────────
def make_anon_id(patient_uuid: str) -> str:
    return hashlib.sha256(str(patient_uuid).encode()).hexdigest()[:12]


def compute_age(birth_date: pd.Timestamp, ref_date: pd.Timestamp) -> int:
    return int((ref_date - birth_date).days / 365.25)


def has_normal_encounter(text: str) -> bool:
    s = ("" if pd.isna(text) else str(text)).casefold()
    return any(kw in s for kw in NORMAL_ENCOUNTER_KEYWORDS)


# ── Load ─────────────────────────────────────────────────────────────────────
def load_synthea(synthea_dir: Path) -> dict:
    """Load required Synthea CSV files from the given directory."""
    required = ["patients", "observations", "conditions", "encounters"]
    data = {}
    for name in required:
        path = synthea_dir / f"{name}.csv"
        if not path.exists():
            raise FileNotFoundError(
                f"Required Synthea file not found: {path}\n"
                f"Run Synthea first — see bime/README_synthea.md"
            )
        data[name] = pd.read_csv(path, low_memory=False)
        print(f"  Loaded {name}.csv  ({len(data[name]):,} rows)")

    # Organizations (optional — enriches department_name with real org names)
    org_path = synthea_dir / "organizations.csv"
    data["organizations"] = (
        pd.read_csv(org_path) if org_path.exists()
        else pd.DataFrame(columns=["Id", "NAME"])
    )
    return data


# ── Filter ───────────────────────────────────────────────────────────────────
def filter_patients(patients_df: pd.DataFrame) -> pd.DataFrame:
    """Keep female patients who are alive."""
    df = patients_df.copy()
    df["BIRTHDATE"] = pd.to_datetime(df["BIRTHDATE"], errors="coerce")
    df = df[df["GENDER"] == "F"]
    df = df[df["DEATHDATE"].isna()]
    return df


def get_hb_observations(obs_df: pd.DataFrame, patient_ids: set) -> pd.DataFrame:
    """Extract and clean hemoglobin measurements for the filtered patients."""
    hb = obs_df[
        (obs_df["CODE"] == HB_LOINC) &
        (obs_df["PATIENT"].isin(patient_ids))
    ].copy()
    hb["DATE"] = pd.to_datetime(hb["DATE"], errors="coerce")
    hb["VALUE"] = pd.to_numeric(hb["VALUE"], errors="coerce")
    hb = hb.dropna(subset=["DATE", "VALUE"])
    return hb.sort_values(["PATIENT", "DATE"]).reset_index(drop=True)


# ── perRI ────────────────────────────────────────────────────────────────────
def compute_perri(hb_df: pd.DataFrame) -> pd.DataFrame:
    """
    For each patient with ≥ MIN_HB_MEASUREMENTS readings, compute:
      hb_result         — most recent HB value
      setpoint          — mean of up to MAX_SETPOINT_TESTS preceding values
      sigma             — std of those values (floored at 0.10 g/dL)
      ci_lower/upper    — setpoint ± 1.96 * sigma
      drop_from_setpoint— setpoint − hb_result (positive = dropped below baseline)
      isolated_tests_count — number of historical readings used
    """
    records = []
    for patient_id, group in hb_df.groupby("PATIENT"):
        group = group.sort_values("DATE").reset_index(drop=True)
        if len(group) < MIN_HB_MEASUREMENTS:
            continue

        latest = group.iloc[-1]
        history = group.iloc[:-1].tail(MAX_SETPOINT_TESTS)

        setpoint = history["VALUE"].mean()
        sigma = history["VALUE"].std(ddof=1) if len(history) > 1 else 0.50
        sigma = max(sigma, 0.10)

        records.append({
            "PATIENT":              patient_id,
            "hb_result":            latest["VALUE"],
            "hb_result_ts":         latest["DATE"],
            "ENCOUNTER":            latest.get("ENCOUNTER", None),
            "setpoint":             setpoint,
            "sigma":                sigma,
            "ci_lower":             setpoint - 1.96 * sigma,
            "ci_upper":             setpoint + 1.96 * sigma,
            "drop_from_setpoint":   setpoint - latest["VALUE"],
            "isolated_tests_count": len(history),
        })
    return pd.DataFrame(records)


# ── Binning & priority ───────────────────────────────────────────────────────
def assign_bins_and_priority(df: pd.DataFrame) -> pd.DataFrame:
    """Apply hb_bin, delta_bin, bucket, and Priority — mirrors src/helper.py."""
    df = df.copy()

    df["hb_bin"] = np.select(
        [df["hb_result"] < 12.5, df["hb_result"] <= 14.5],
        HB_LABELS,
        default="EXCLUDE",
    )

    df["delta_bin"] = pd.cut(
        df["drop_from_setpoint"],
        bins=DELTA_BINS,
        labels=DELTA_LABELS,
        right=True,
        include_lowest=True,
    ).astype("object").fillna("EXCLUDE")

    df["bucket"] = np.where(
        (df["hb_bin"] != "EXCLUDE") & (df["delta_bin"] != "EXCLUDE"),
        df["hb_bin"] + " x " + df["delta_bin"],
        "",
    )
    df = df[df["bucket"].ne("")].copy()

    df["delta_bin_rank"] = df["delta_bin"].map(DELTA_TIER).fillna(0)
    df["normal_bonus"] = df["mapped_dx_names"].apply(has_normal_encounter)

    # Mirror the real pipeline: 'HB ≤ 14.5 x [-0.5, 0.5)' only if normal encounter
    df = df[~(
        (df["bucket"] == "HB ≤ 14.5 x [-0.5, 0.5)") & (~df["normal_bonus"])
    )]

    df["Priority"] = (
        df["delta_bin_rank"] * DELTA_TIER_WEIGHT
        + np.where(df["hb_result"] < 12.5, HB_LOW_WEIGHT, HB_NORM_WEIGHT)
        + np.where(df["normal_bonus"], HEALTHY_BONUS, 0)
    )

    return df.sort_values("Priority", ascending=False)


# ── Ferritin simulation ──────────────────────────────────────────────────────
def simulate_ferritin(df: pd.DataFrame, rng: np.random.Generator) -> pd.Series:
    """
    Simulate ferritin (ng/mL) via a log-normal model.

    Synthea's anemia module does NOT generate ferritin lab results (LOINC 2276-4).
    This simulation is calibrated to reproduce the epidemiological relationship
    observed in the real pipeline:

      P(ferritin < 30) increases with larger drop_from_setpoint and lower hb_result.

    Calibration anchors (approximate):
      drop = 0 g/dL → mean ferritin ≈ 80 ng/mL
      drop = 0.5    → mean ferritin ≈ 55 ng/mL
      drop = 1.0    → mean ferritin ≈ 35 ng/mL
      drop ≥ 2.0    → mean ferritin ≈ 18 ng/mL
      HB < 12.5 g/dL reduces expected ferritin by an additional 30 %.

    The log-normal distribution (CV ≈ 50 %) is used to match the right-skewed
    shape of real ferritin distributions.
    """
    drop = df["drop_from_setpoint"].clip(lower=-1.0, upper=5.0).values
    hb = df["hb_result"].values

    mean_fer = 80.0 * np.exp(-0.55 * drop) * np.where(hb < 12.5, 0.70, 1.0)
    mean_fer = np.clip(mean_fer, 8.0, None)

    cv = 0.50
    sigma_ln = np.sqrt(np.log(1 + cv**2))
    mu_ln = np.log(mean_fer) - 0.5 * sigma_ln**2

    simulated = rng.lognormal(mean=mu_ln, sigma=sigma_ln, size=len(df))
    return pd.Series(simulated.round(1), index=df.index)


# ── Encounter info → department / specialty ──────────────────────────────────
def get_encounter_info(
    enc_df: pd.DataFrame,
    orgs_df: pd.DataFrame,
    hb_obs_df: pd.DataFrame,
) -> pd.DataFrame:
    """
    For each patient, find the encounter associated with their most recent HB
    measurement and return department_name and specialty_dep.
    """
    # Most recent HB encounter per patient
    latest_enc = (
        hb_obs_df.sort_values("DATE")
        .groupby("PATIENT", as_index=False)
        .last()[["PATIENT", "ENCOUNTER"]]
    )
    enc_sub = enc_df[["Id", "ENCOUNTERCLASS", "ORGANIZATION"]].copy()
    merged = latest_enc.merge(enc_sub, left_on="ENCOUNTER", right_on="Id", how="left")

    merged["department_name"] = merged["ENCOUNTERCLASS"].map(
        {k: v[0] for k, v in ENCOUNTER_CLASS_MAP.items()}
    ).fillna("Primary Care Clinic")

    merged["specialty_dep"] = merged["ENCOUNTERCLASS"].map(
        {k: v[1] for k, v in ENCOUNTER_CLASS_MAP.items()}
    ).fillna("Family Medicine")

    # Enrich with real organization name when available
    if not orgs_df.empty and "NAME" in orgs_df.columns:
        org_map = orgs_df.set_index("Id")["NAME"].to_dict()
        org_names = merged["ORGANIZATION"].map(org_map)
        has_org = org_names.notna()
        merged.loc[has_org, "department_name"] = org_names[has_org]

    return merged[["PATIENT", "department_name", "specialty_dep"]]


# ── Condition names ───────────────────────────────────────────────────────────
def get_mapped_dx_names(cond_df: pd.DataFrame, hb_df: pd.DataFrame) -> pd.DataFrame:
    """
    For each patient, join condition Descriptions that were active at the time
    of their most recent HB measurement. Result mirrors 'mapped_dx_names'.
    """
    latest_hb = (
        hb_df.groupby("PATIENT")["DATE"].max()
        .reset_index()
        .rename(columns={"DATE": "latest_hb"})
    )
    cond = cond_df.copy()
    cond["START"] = pd.to_datetime(cond["START"], errors="coerce")
    cond["STOP"] = pd.to_datetime(cond["STOP"], errors="coerce")
    cond = cond.merge(latest_hb, on="PATIENT", how="left")

    active = cond[
        (cond["START"] <= cond["latest_hb"]) &
        (cond["STOP"].isna() | (cond["STOP"] >= cond["latest_hb"]))
    ]

    dx_names = (
        active.groupby("PATIENT")["DESCRIPTION"]
        .apply(lambda x: ";".join(sorted(x.dropna().unique())))
        .reset_index()
        .rename(columns={"DESCRIPTION": "mapped_dx_names"})
    )
    return dx_names


# ── Diagnoses CSV ─────────────────────────────────────────────────────────────
def build_diagnoses(cond_df: pd.DataFrame, id_map: dict) -> pd.DataFrame:
    """Map Synthea SNOMED conditions → ICD-10 and anonymize patient IDs."""
    df = cond_df[cond_df["PATIENT"].isin(id_map)].copy()
    df["icd10_code"] = df["CODE"].astype(str).map(SNOMED_TO_ICD10).fillna("")
    df["icd9_code"] = ""   # Synthea does not produce ICD-9 codes
    df["anon_id"] = df["PATIENT"].map(id_map)
    df = df.rename(columns={"START": "contact_date"})
    return (
        df[["anon_id", "icd9_code", "icd10_code", "contact_date"]]
        .drop_duplicates()
        .reset_index(drop=True)
    )


# ── Main ──────────────────────────────────────────────────────────────────────
def curate(synthea_dir: Path, seed: int = 42) -> None:
    rng = np.random.default_rng(seed)

    print(f"\n{'='*60}")
    print(f"BIME Digital Twins — curate_data.py")
    print(f"Synthea source: {synthea_dir}")
    print(f"{'='*60}\n")

    # 1. Load
    print("Loading Synthea CSVs...")
    data = load_synthea(synthea_dir)

    # 2. Filter patients: female, alive
    patients_f = filter_patients(data["patients"])
    patient_ids = set(patients_f["Id"].unique())
    print(f"\nFiltered to {len(patient_ids):,} female patients (alive)")

    # 3. Extract HB observations
    hb_obs = get_hb_observations(data["observations"], patient_ids)
    pts_with_hb = hb_obs["PATIENT"].nunique()
    print(f"Found {len(hb_obs):,} HB observations (LOINC {HB_LOINC}) "
          f"across {pts_with_hb:,} patients")

    # 4. Compute perRI (filters to ≥ MIN_HB_MEASUREMENTS)
    print(f"\nComputing perRI (requiring ≥ {MIN_HB_MEASUREMENTS} HB readings)...")
    perri_df = compute_perri(hb_obs)
    print(f"  {len(perri_df):,} patients with sufficient HB history")

    if perri_df.empty:
        print(
            "\nNo patients met the minimum HB history requirement.\n"
            "Try generating more patients or reducing MIN_HB_MEASUREMENTS."
        )
        return

    # 5. Age at most recent HB (apply 18–65 filter)
    birth_map = patients_f.set_index("Id")["BIRTHDATE"].to_dict()
    perri_df["age"] = perri_df.apply(
        lambda r: compute_age(
            pd.to_datetime(birth_map.get(r["PATIENT"])),
            r["hb_result_ts"],
        ),
        axis=1,
    )
    perri_df = perri_df[(perri_df["age"] >= 18) & (perri_df["age"] <= 65)]
    print(f"  {len(perri_df):,} patients aged 18–65 at time of most recent HB")

    # 6. Encounter info (department / specialty)
    enc_info = get_encounter_info(data["encounters"], data["organizations"], hb_obs)
    perri_df = perri_df.merge(enc_info, on="PATIENT", how="left")
    perri_df["department_name"] = perri_df["department_name"].fillna("Primary Care Clinic")
    perri_df["specialty_dep"] = perri_df["specialty_dep"].fillna("Family Medicine")

    # 7. Condition descriptions (mapped_dx_names)
    dx_names_df = get_mapped_dx_names(data["conditions"], hb_obs)
    perri_df = perri_df.merge(dx_names_df, on="PATIENT", how="left")
    perri_df["mapped_dx_names"] = perri_df["mapped_dx_names"].fillna("")

    # 8. Bins, buckets, priority (mirrors src/helper.py)
    print("\nAssigning bins and priority scores...")
    perri_df = assign_bins_and_priority(perri_df)
    print(f"  {len(perri_df):,} patients after binning filters")

    if perri_df.empty:
        print("Warning: no patients remained after binning. Check HB value distributions.")
        return

    # 9. Simulate ferritin (log-normal model — see docstring)
    print("\nSimulating ferritin values...")
    perri_df["ferritin"] = simulate_ferritin(perri_df, rng)
    p30 = (perri_df["ferritin"] < 30).mean()
    print(f"  Simulated ferritin: mean={perri_df['ferritin'].mean():.1f}, "
          f"P(ferritin<30)={p30:.1%}")

    # 10. Anonymize
    id_map = {pid: make_anon_id(pid) for pid in perri_df["PATIENT"].unique()}
    perri_df["anon_id"] = perri_df["PATIENT"].map(id_map)

    # 11. Build patients.csv
    PATIENT_COLS = [
        "anon_id", "age", "hb_result", "hb_result_ts", "setpoint", "sigma",
        "ci_lower", "ci_upper", "drop_from_setpoint", "department_name",
        "specialty_dep", "mapped_dx_names", "hb_bin", "delta_bin", "bucket",
        "Priority", "isolated_tests_count", "ferritin",
    ]
    patients_out = perri_df[[c for c in PATIENT_COLS if c in perri_df.columns]].copy()

    # 12. Build hb_trajectories.csv
    hb_traj = hb_obs[hb_obs["PATIENT"].isin(id_map)].copy()
    hb_traj["anon_id"] = hb_traj["PATIENT"].map(id_map)
    hb_traj = (
        hb_traj.rename(columns={"DATE": "result_ts", "VALUE": "result_value"})
        [["anon_id", "result_ts", "result_value"]]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    # 13. Build diagnoses.csv
    diagnoses_out = build_diagnoses(data["conditions"], id_map)

    # 14. Save
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    patients_out.to_csv(OUTPUT_DIR / "patients.csv", index=False)
    hb_traj.to_csv(OUTPUT_DIR / "hb_trajectories.csv", index=False)
    diagnoses_out.to_csv(OUTPUT_DIR / "diagnoses.csv", index=False)

    print(f"\n{'='*60}")
    print(f"Saved {len(patients_out):,} patients     → {OUTPUT_DIR / 'patients.csv'}")
    print(f"Saved {len(hb_traj):,} HB measurements → {OUTPUT_DIR / 'hb_trajectories.csv'}")
    print(f"Saved {len(diagnoses_out):,} dx records     → {OUTPUT_DIR / 'diagnoses.csv'}")

    # 15. Bucket summary
    print(f"\nBucket distribution:")
    for bucket, n in perri_df["bucket"].value_counts().items():
        print(f"  {bucket}: {n}")

    # 16. Verify no PII leaked
    pii_check = {"PATIENT", "SSN", "DRIVERS", "PASSPORT", "FIRST", "LAST", "Id"}
    for name, df in [("patients", patients_out), ("hb_traj", hb_traj), ("diagnoses", diagnoses_out)]:
        leaked = pii_check & set(df.columns)
        assert not leaked, f"PII columns found in {name}: {leaked}"
    print("\nVerification passed: no PII columns in output files.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Curate Synthea data into BIME digital-twins demo CSVs"
    )
    parser.add_argument(
        "--synthea-dir",
        type=Path,
        default=DEFAULT_SYNTHEA_DIR,
        help=(
            "Path to Synthea CSV output directory "
            "(default: bime/synthea_output/csv)"
        ),
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for ferritin simulation (default: 42)",
    )
    args = parser.parse_args()
    curate(args.synthea_dir, seed=args.seed)
